### ISSUE TITLE
Use library with Processing 2.2.1

### ISSUE THREAD

**Issue by chr33z** [taksan/skype-java-api#53]
Is it possible to use this library with processing 2.2.1?
I'm trying to import the library in a sketch but end up getting a
```
Syntax error on token "enum", Identifier expected
```
with no further information where in the library the error might occur.

The error is definitely thrown in the library because my sketch looks just like this:
```
import com.skype.Skype;

void setup(){}
```

Thank you for any help on this issue!

**Comment by taksan** [comment]
This is not an actual issue, so I'm closing.
