### ISSUE TITLE
I FIGURED SOMETHING OUT :P

### ISSUE THREAD

**Issue by DrZed** [taksan/skype-java-api#65]
http://puu.sh/j8dg1.png

That's old groups and priv chat

http://puu.sh/j8dhB.png

New Groups Aparently are threaded. I'm not very fluid in multithreading or poking other threads...
Maybe someone else is....

**Comment by Cuniq** [comment]
This api works only with p2p and 2 person chats. If you add one person to an existing chat it creates a cloud based chat in which api won't work.

I see that you are creating a bot if you like you could help me work together on mine https://github.com/Cuniq/SkypeBot

**Comment by DrZed** [comment]
You're slightly wrong on that my bot reads the chat fine

**Comment by DrZed** [comment]
I need to get the chat from the other skype thread and send a message through it, but I'm not good at working with threads

**Comment by Cuniq** [comment]
If your chat is old enough it may be p2p. Try creating a new chat and tell me if it works.

I can't understand what you want. You need to take one message from one chat and send it to another one?

**Comment by DrZed** [comment]
BTW This chat was only 2 hours old... I created it with those 2 in the call when fern woke up...

**Comment by DrZed** [comment]
old chats are visible because they're not threaded, new chats are threaded since they're downloaded from the cloud to reduce lag they get their own thread... I know this because I'm using windows 10 and Visual Studio 2015 RTM and viewing the decompiled code..

**Comment by dretax** [comment]
Oh shit. Do you know where exactly they store the threads?

**Comment by DrZed** [comment]
Just the data I gathered in the screenshots I know not much more... :/ decompiled code is garbage in all reality :/ (for me anyway)

**Comment by dretax** [comment]
=(

**Comment by Itsprime** [comment]
:{
