### ISSUE TITLE
Skype.getContactList().getAllFriends() not working in linux

### ISSUE THREAD

**Issue by nfacha** [taksan/skype-java-api#66]
Hello
Skype.getContactList().getAllFriends() will be empty in linux(ubuntu 14.04)
The same code/compiled jar works on windows

**Comment by FFY00** [comment]
You can use this:

ContactList contatos = Skype.getContactList();
        Friend amigos[] = contatos.getAllFriends();
        for(int i=0; i < amigos.length; i++){
        ClasseDasVariaveis.numeroContatos++;
}

I've tested it in linux, works for me xD

**Comment by nfacha** [comment]
@FFY00 
Not working here:
´´´java
    public static int getTotal() throws SkypeException {
        int c = 0;
        //Implementacao de https://github.com/taksan/skype-java-api/issues/66
        ContactList contatos = Skype.getContactList();
        Friend amigos[] = contatos.getAllFriends();
        for (int i = 0; i < amigos.length; i++) {
            c++;
        }
        return c;
    }
´´´

**Comment by Cuniq** [comment]
since you guys trying to make something like i allready did you may want to use and even better continue my bot https://github.com/Cuniq/SkypeBot. Bot of the issues here are trying to make something like this.

**Comment by nfacha** [comment]
@Cuniq I already have my bot running in wondows, i kust need help to get it working on linux on that sepecify method

@taksan

**Comment by FFY00** [comment]
@Cuniq me and @nfacha already have a bot running... you can add it if you want to: squirrel.bot

I've tested that code in my Kali Linux (using Debian 7 32bits) and it worked fine: http://pastebin.com/YyYAzs4L
