### ISSUE TITLE
Doesn't work when process is elevated

### ISSUE THREAD

**Issue by TheRandomLabs** [taksan/skype-java-api#77]
I'm writing an application that may potentially need elevation, but I've discovered that Skype Java API throws a NotAttachedException when I try to add a `ChatMessageListener`, and I suspect any other listener.

**Comment by Cuniq** [comment]
@TheRandomLabs Are you sure that skype client is running? And if it does when you run your code you have to go at your skype client click accept at the notification which created at the top of the window.

If you like you can check also my [bot](https://github.com/Cuniq/SkypeBot). It may serve your needs

**Comment by TheRandomLabs** [comment]
Yes, the Skype client is running, and it works when the process is not elevated. I have already clicked accept for two different java.exe and javaw.exes.
