### ISSUE TITLE
I cannot able to call from my java application using new version of skype 

### ISSUE THREAD

**Issue by nilkanth0018** [taksan/skype-java-api#86]
When I try to call from my java application using skype API it cannot call. It try to call but it shows me different ID which you can see in below link of image. I am using this method:
Skype.call(String SKYPE_ID);
Please help me!!! 
http://content.screencast.com/users/kp_viral/folders/Jing/media/4cb71069-467a-4d06-bd72-f5efa88e0859/2016-11-22_1207.png

**Comment by FFY00** [comment]
Microsoft has drooped support for the desktop API.

**Comment by nilkanth0018** [comment]
@FFY00 So is there any other way to connect Skype with Java Desktop Application? Please Help

**Comment by FFY00** [comment]
@nilkanth0018 I believe you can use Skype Web SDK but there's no java api yet as far as I know.

Here: https://msdn.microsoft.com/Skype/WebSDK/docs/SkypeWebSDK

**Comment by taksan** [comment]
Just be warned:

**"Applies to: Skype for Business 2015, Skype for Business Online"**
